import time
import turtle
def map():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
def map_2():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(50)
    time.sleep(5)
def map_3():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.right(90)
    time.sleep(5)
def map_4():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    time.sleep(5)

def map_5():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    time.sleep(5)
print("this was made by CONTUNUM PROGRAMING")
def game_over():
    print("game over")
    time.sleep(1)
    game_over()
time.sleep(1)
print("pleas have in full screen")
time.sleep(1)
name = input("what is your name: ")
print("hi",name)
time.sleep(1)
friend_name = input("what is your best friend's name: ")
time.sleep(1)
print("You are in the carrabean on a unknown island.")
time.sleep(1)
print("you were in a plane crash with",friend_name,"everyone else died.")
time.sleep(1)
print("  ______  __    __       ___      .______   .___________. _______ .______          __  ")
print(" /      ||  |  |  |     /   \     |   _  \  |           ||   ____||   _  \        /_ | ")
print("   ,----'|  |__|  |    /  ^  \    |  |_)  | `---|  |----`|  |__   |  |_)  |        | | ")
print("|  |     |   __   |   /  /_\  \   |   ___/      |  |     |   __|  |      /         | | ")
print("|  `----.|  |  |  |  /  _____  \  |  |          |  |     |  |____ |  |\  \----.    | | ")
print(" \______||__|  |__| /__/     \__\ | _|          |__|     |_______|| _| `._____|    |_| ")                                                                                    
time.sleep(5)
print('you : hey',friend_name)
time.sleep(1)
print(friend_name,': yes')
time.sleep(1)
print('you : are you okay?')
time.sleep(1)
print(friend_name,': yes')
time.sleep(1)
print(friend_name,": what are we going to eat other than the Doritos from the plane?")
time.sleep(1)
print(friend_name,": coconut. (not)")
time.sleep(1)
food=input("do you want cocunut or watermelon")
print("okay") 
time.sleep(1)
print(friend_name,": i will go get some",food)
time.sleep(1)
print(friend_name,": go set up the tent. okay?")
tent=input()
if tent=="no":
    game_over()
if tent=="yes":
    print("later that day")
time.sleep(1)
print("it is time to go to bed")
time.sleep(1)
print(" ______  __    __       ___      .______   .___________. _______ .______          ___   ") 
print(" /      ||  |  |  |     /   \     |   _  \  |           ||   ____||   _  \        |__ \  ") 
print("|  ,----'|  |__|  |    /  ^  \    |  |_)  | `---|  |----`|  |__   |  |_)  |          ) | ") 
print("|  |     |   __   |   /  /_\  \   |   ___/      |  |     |   __|  |      /          / /  ") 
print("|  `----.|  |  |  |  /  _____  \  |  |          |  |     |  |____ |  |\  \----.    / /_  ") 
print(" \______||__|  |__| /__/     \__\ | _|          |__|     |_______|| _| `._____|   |____| ") 
time.sleep(5)
print("you : yawn.")
time.sleep(1)
print("you : hay",friend_name)
time.sleep(1)
print("you : hmm, no answer")
time.sleep(1)
print("outside of the banana leaf tent")
time.sleep(1)
print("you : there are footprints. mabye",friend_name,"is getting wood")
time.sleep(1)
print("you : why are there other footprints that",friend_name,"did not make")
time.sleep(1)
map1=input("do you want to open the map ")
if map1=="yes":
    map()
print("the dot is",friend_name,"and the arrow is you")
di1=input("do you go right or left ")
if di1 == "left":
    game_over()
map2=input("do you want to open the map ")
if map2=="yes":
    map_2()
    time.sleep(1)
di2=input("do you go right or left ")
if di2=="left":
    game_over()
map3=input("do you want to open the map ")
if map3=="yes":
    map_3()
time.sleep(1)
di3=input("do you go forward or backward ")
if di3=="backward":
    game_over()
map4=input("do you want to open the map ")
if map4=="yes":
    map_4()
time.sleep(1)
di4=input("do you go forward or backward ")
if di4=="backward":
    game_over()
map5=input("do you want to open the map ")
if map5=="yes":
    map_5()
time.sleep(1)
print("kidnaper 1 : da boss will be mad dat our secret base was found")
time.sleep(1)
print("kidnaper 2 : yah")
time.sleep(1)
print(friend_name,":mphmfph")
at1 = input("do you want to go in now or wait till night ")
if at1 == ("wait till night"):
     print("kidnapper 1 : *yawn* me go to bed")
else:
    game_over()
