import time
import turtle
from os import system
system("title " + "Stranded")
def intro():
    turtle.reset()
    turtle.right(15)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.penup()
    turtle.goto(x=0, y=0)
    turtle.right(180)
    turtle.forward(115)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.right(180)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.right(180)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.right(180)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.right(180)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.right(180)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.right(180)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.right(180)
    turtle.penup()
    turtle.forward(115)
    turtle.pendown()
    turtle.right(180)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.forward(50)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.left(15)
    turtle.forward(5)
    turtle.right(180)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(800)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(1600)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(138)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(1600)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(200)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(400)
    turtle.left(160)
    turtle.forward(425)
    turtle.penup()
    turtle.setheading(-15)
    turtle.backward(146)
    turtle.left(90)
    turtle.forward(188)
    turtle.pendown()
    turtle.forward(400)
    turtle.right(160)
    turtle.forward(425)
    time.sleep(10)
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    print("the dot is the plane")
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.goto(x=0,y=0)
    turtle.pendown()
    turtle.dot(10)
    turtle.penup()
    turtle.goto(x=1000,y=1000)
def map():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
def map_2():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(50)
    time.sleep(5)
def map_3():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.right(90)
    time.sleep(5)
def map_4():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    time.sleep(5)

def map_5():
    turtle.reset()
    turtle.penup()
    turtle.forward(440)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(380)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(770)
    turtle.right(90)
    turtle.forward(890)
    turtle.right(90)
    turtle.forward(390)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(240)
    turtle.penup()
    turtle.goto(x=100,y=100)
    turtle.pendown()
    turtle.dot(size=10)
    turtle.penup()
    turtle.goto(x=0,y=0)
    turtle.right(135)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    time.sleep(5)
print("Created by eanderso2")
time.sleep(1)
print("Bug-fixed by ThePTNT")
time.sleep(1)
print("Easter eggs added/Tested by xorb999999999")
time.sleep(1)
print("Made in 1 year")
time.sleep(1)
print("Coding finished on August 24th, 2021")
time.sleep(1)
print("Now, without further ado...")
def game_over():
    print("You lost! Game will close in 5 seconds.")
    time.sleep(5)
    quit()
time.sleep(1)
print("Please have python window maximized.")
time.sleep(1)
name = input("What is your name? ")
print("Hello,",name)
time.sleep(1)
friend_name = input("What is your best friend's name? ")
time.sleep(1)
print("You are in the carribean, on an undiscovered island.")
intro()
time.sleep(1)
print("  ______  __    __       ___      .______   .___________. _______ .______          __  ")
print(" /      ||  |  |  |     /   \     |   _  \  |           ||   ____||   _  \        /_ | ")
print("   ,----'|  |__|  |    /  ^  \    |  |_)  | `---|  |----`|  |__   |  |_)  |        | | ")
print("|  |     |   __   |   /  /_\  \   |   ___/      |  |     |   __|  |      /         | | ")
print("|  `----.|  |  |  |  /  _____  \  |  |          |  |     |  |____ |  |\  \----.    | | ")
print(" \______||__|  |__| /__/     \__\ | _|          |__|     |_______|| _| `._____|    |_| ")                                                                                    
time.sleep(5)
print('You: Hey,',friend_name)
time.sleep(1)
print(friend_name,': Yes?')
time.sleep(1)
print('You: Are you okay?')
time.sleep(1)
print(friend_name,': Yes...')
time.sleep(1)
print("You: What are we going to eat other than the Doritos from the plane?")
time.sleep(1)
print(friend_name,": coconut. (not)")
time.sleep(1)
food=input("Do you want coconut or watermelon?")
print(friend_name,": Okay.") 
time.sleep(1)
print(friend_name,": I will go try and find some",food)
time.sleep(1)
print(friend_name,": Go set up the tent, Okay?")
time.sleep(1)
print("...")
time.sleep(1.5)
print("Later that day...")
time.sleep(1)
print("You: It's time to go to bed,",friend_name)
time.sleep(1)
print(" ______  __    __       ___      .______   .___________. _______ .______          ___   ") 
print(" /      ||  |  |  |     /   \     |   _  \  |           ||   ____||   _  \        |__ \  ") 
print("|  ,----'|  |__|  |    /  ^  \    |  |_)  | `---|  |----`|  |__   |  |_)  |          ) | ") 
print("|  |     |   __   |   /  /_\  \   |   ___/      |  |     |   __|  |      /          / /  ") 
print("|  `----.|  |  |  |  /  _____  \  |  |          |  |     |  |____ |  |\  \----.    / /_  ") 
print(" \______||__|  |__| /__/     \__\ | _|          |__|     |_______|| _| `._____|   |____| ") 
time.sleep(5)
print("You : Yawn....")
time.sleep(1)
print("You : Hey",friend_name)
time.sleep(3)
print("You : Hmm,",friend_name,"isn't answering.")
time.sleep(1)
print("Outside of the banana leaf tent...")
time.sleep(1)
print("You: There are footprints. Maybe",friend_name,"is finding breakfast?")
time.sleep(1)
print("You: Why are there other footprints that",friend_name,"didn't make?")
time.sleep(1)
map1=input("Do you want to open the map? Type 'yes' to open map. ")
if map1=="yes":
    map()
else:
    print("Why wouldn't you say yes???")
    time.sleep(2)
    game_over()
print("The dot is",friend_name," and the arrow is you")
dir1=input("do you want to go right or left")
if dir1 == "left":
    print("You went left and encountered a group of man eating baboons. Good job. You died.")
    time.sleep(2)
    game_over()
map2=input("Do you want to open the map? Type 'yes' to open map. ")
if map2=="yes":
    map_2()
    time.sleep(1)
else:
    print("Why wouldn't you say yes???")
    time.sleep(2)
    game_over()
dir2=input("Do you go right or left?")
if dir2=="left":
    print("You went left, and ended back up at your tent, where you found a group of wolves eating your doritos. You died.")
    time.sleep(2)
    game_over()
map3=input("Do you want to open the map? Type 'yes' to open map. ")
if map3=="yes":
    map_3()
    time.sleep(1)
else:
    print("Why wouldn't you say yes???")
    time.sleep(2)
    game_over()
dir3=input("do you want to go south(down) ot north(up)")
if dir3=="south":
    print("You went south, and found a shack.")
    time.sleep(1)
    print("You entered the shack, and found a man inside saying 'AHAHAHAHAH! It's ALIVE!'.")
    time.sleep(1)
    print("By now you realize that frankenstein has ripped your head off. You Died.")
    time.sleep(1)
    game_over()
map4=input("Do you want to open the map? Type 'yes' to open map. ")
if map4=="yes":
    map_4()
    time.sleep(1)
else:
    print("Why wouldn't you say yes???")
    time.sleep(2)
    game_over()
dir4=input("do you want to go north(up) or soyth(down). ")
if dir4=="south":
    print("You went back to where you were before. You hear some shouting, and then you see frankenstein.")
    time.sleep(1)
    print("After that, You Ded. You have failed. Great job.")
    time.sleep(1)
    game_over()
map5=input("Do you want to open the map? Type 'yes' to open map. ")
if map5=="yes":
    map_5()
    time.sleep(1)
else:
    print("Why wouldn't you say yes???")
    time.sleep(2)
    game_over()
print("Robert the Kidnapper: Da boss will be mad dat our secret base was found....")
time.sleep(1)
print("Bobert the Kidnapper: Yeh...")
time.sleep(1)
print(friend_name,": MPMFHFPM!!")
at1 = input("Do you want to go in now, or wait till night? Type 'now' to go in now, or type 'later' to go at night. ")
if at1 == ("later"):
     print("Robert: *Y A W N*, I am gonna go to bed.")
else:
    print("You went in, and you died. Lol")
    game_over()
print("Bobert: Me too.")
time.sleep(1)
print("You sneak in and as you finish untying",friend_name,"Robert wakes up.")
time.sleep(1)
print("Robert: Bobert! What are you doing?")
time.sleep(1)
print("Robert: Wait, YOU'RE NOT BOBERT!!!")
time.sleep(1)
print("You spot a cave in the secret base.")
time.sleep(1)
print("You decide to run into the cave. You run deeper and deeper...")
time.sleep(1)
print("You hear water on the left.")
time.sleep(1)
print("You see a waterfall with light on the other side.")
time.sleep(1)
print("You go left...")
time.sleep(1)
print("You go through the waterfall...")
time.sleep(3)
print("...")
time.sleep(3)
print("You jump")
time.sleep(3)
print("And you land")
time.sleep(3)
print("And you get squished by",friend_name)
print(friend_name,": We escaped Robert and Bobert!!!!!!!!!!!!!!!!!")
print(".___________. __    __   _______     _______ .__   __.  _______   __   __   __  ")
print("|           ||  |  |  | |   ____|   |   ____||  \ |  | |       \ |  | |  | |  | ")
print("`---|  |----`|  |__|  | |  |__      |  |__   |   \|  | |  .--.  ||  | |  | |  | ")
print("    |  |     |   __   | |   __|     |   __|  |  . `  | |  |  |  ||  | |  | |  | ")
print("    |  |     |  |  |  | |  |____    |  |____ |  |\   | |  '--'  ||__| |__| |__| ")
print("    |__|     |__|  |__| |_______|   |_______||__| \__| |_______/ (__) (__) (__) ")
time.sleep(3)
print("or is it")
print("you win")
quit()
